exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

plugins:
  - jekyll-sitemap

github:
  private: false
  license:
    name: MIT
  source:
    branch: "main"
    path: "/"
  repository_url: "https://github.com/jamesmacwhite/vm-whynoipv6"

twitter:
  username: jamesmacwhite

lang: en-GB
title: Have Virgin Media deployed IPv6 yet?
description: Raising awareness about the lack of IPv6 on Virgin Media Broadband
lead_text:  Virgin Media like many UK Internet Service Providers (ISPs) have not yet deployed IPv6. While this isn't breaking news because loads of ISPs suffer from IPv6 deployment lag (since December 1995), Virgin Media UK has an interesting IPv6 story which is why I felt I needed to create this page, to inform others who may be looking at IPv6 (or the lack of) and happen to be a Virgin Media customer.
google_analytics: UA-39273437-3
change_org_petition_url: https://www.change.org/virginmediaipv6
twitter_sharer_url: http://twitter.com/share?text=@virginmedia You should really think about enabling IPv6&url=https://havevirginmediaenabledipv6yet.co.uk
